# tasks_config.yaml - 任务配置文件
#
# 该文件用于配置gorepe.py要执行的任务列表，分为三类：
# 1. init_programs: 初始化程序，按顺序执行，通常为基础数据获取
# 2. serial_programs: 串行程序，按顺序执行，但可以有多个工作进程
# 3. parallel_programs: 并行程序，可以并行执行，通常为大量数据获取任务
#
# 所有路径都是相对于项目根目录的相对路径

# 初始化程序 - 按顺序执行
# 这些程序通常获取基础数据，如交易日历、股票列表等
init_programs:
  - trade_cal_fetcher.py      # 交易日历获取器
  - stock_basic_fetcher.py    # 股票基本信息获取器


# 串行程序 - 按顺序执行，但可以有多个工作进程
# 这些程序需要按特定顺序执行，但内部可以并行处理
serial_programs:
  # - basic_indicator_fetcher.py  # 基本面指标数据获取器
  - monthly_fetcher.py          # 日线数据获取器

# 并行程序 - 可以并行执行
# 这些程序可以同时执行，通常为大量数据获取任务
parallel_programs:
  - daily_fetcher.py          # 日线数据获取器
  - daily_basic_fetcher.py    # 每日指标获取器
  - div_fetcher.py            # 分红数据获取器
  - moneyflow_fetcher.py      # 资金流向数据获取器
  - monthly_fetcher.py        # 月线数据获取器
  - stk_managers_fetcher.py   # 管理层信息获取器
  - stk_rewards_fetcher.py    # 管理层薪酬和持股获取器
  - stock_company_fetcher.py  # 上市公司基本信息获取器  
  - stock_previous_name_fetcher.py # 股票曾用名获取器
  - suspend_fetcher.py        # 停复牌信息获取器
  - weekly_fetcher.py         # 周线数据获取器



