# tasks_config.yaml - 任务配置文件
#
# 该文件用于配置gorepe.py要执行的任务列表，分为三类：
# 1. init_programs: 初始化程序，按顺序执行，通常为基础数据获取
# 2. serial_programs: 串行程序，按顺序执行，但可以有多个工作进程
# 3. parallel_programs: 并行程序，可以并行执行，通常为大量数据获取任务
#
# 所有路径都是相对于项目根目录的相对路径

# 初始化程序 - 按顺序执行
# 这些程序通常获取基础数据，如交易日历、股票列表等
init_programs:
  - trade_cal_fetcher.py      # 交易日历获取器
  - stock_basic_fetcher.py    # 股票基本信息获取器


# 串行程序 - 按顺序执行，但可以有多个工作进程
# 这些程序需要按特定顺序执行，但内部可以并行处理
serial_programs:
  # - basic_indicator_fetcher.py  # 基本面指标数据获取器
  - monthly_fetcher.py          # 日线数据获取器

# 并行程序 - 可以并行执行
# 这些程序可以同时执行，通常为大量数据获取任务
parallel_programs:
  - daily_fetcher.py          # 日线数据获取器
  - daily_basic_fetcher.py    # 每日指标获取器
  - div_fetcher.py            # 分红数据获取器
  - moneyflow_fetcher.py      # 资金流向数据获取器
  - monthly_fetcher.py        # 月线数据获取器
  - stk_managers_fetcher.py   # 管理层信息获取器
  - stk_rewards_fetcher.py    # 管理层薪酬和持股获取器
  - stock_company_fetcher.py  # 上市公司基本信息获取器  
  - stock_previous_name_fetcher.py # 股票曾用名获取器
  - suspend_fetcher.py        # 停复牌信息获取器
  - weekly_fetcher.py         # 周线数据获取器
  - balancesheet_fetcher.py    # 资产负债表数据获取器
  - income_fetcher.py         # 利润表数据获取器
  - cashflow_fetcher.py       # 现金流量表数据获取器
  - express_fetcher.py        # 主要财务指标数据获取器
  - forecast_fetcher.py       # 业绩预告数据获取器
  - ggt_daily_fetcher.py      # 港通日线数据获取器
  - ggt_monthly_fetcher.py    # 港通月线数据获取器
  - ggt_sh_daily_fetcher.py   # 沪股通日线数据获取器
  - ggt_top10_fetcher.py     # 港通十大成交股数据获取器
  - hk_hold_fetcher.py       # 港股通持股数据获取器
  - hsgt_top10_fetcher.py    # 沪深港通十大成交股数据获取器
  - limit_list_d_fetcher.py   # 涨停榜数据获取器
  - stk_limit_fetcher.py      # 涨停数据获取器
  - fin_indicator_fetcher.py  # 财务指标数据获取器
  - block_trade_fetcher.py   # 大宗交易数据获取器
  - concept_fetcher.py       # 概念数据获取器
  - concept_detail_fetcher.py # 概念详情数据获取器
  - dividend_fetcher.py      # 分红数据获取器
  - margin_detail_fetcher.py # 融资融券数据获取器
  - margin_fetcher.py        # 融资融券数据获取器
  - pledge_detail_fetcher.py # 质押数据获取器
  - pledge_stat_fetcher.py   # 质押统计数据获取器
  - repurchase_fetcher.py     # 回购数据获取器
  - stk_holdernumber_fetcher.py # 股东人数数据获取器
  - stk_holdertrade_fetcher.py # 股东交易数据获取器
  - top_inst_fetcher.py        # 机构持股数据获取器
  - top_list_fetcher.py        # 龙虎榜数据获取器
  - top10_holders_fetcher.py  # 前十大股东数据获取器
  - top10_floatholders_fetcher.py # 前十大流通股东数据获取器

  
  



